// Precomputed impact data, imported at build time.
//
// For the `precomputed` data pattern the "fixture" is the real, committed
// dataset generated by scripts/precompute.py. The frontend imports it directly;
// there is no runtime backend. The values below are placeholder stubs until
// scripts/precompute.py is run against the hosted PolicyEngine API — see the
// backend-builder phase.
import impactData from '../../public/data/impact.json'
import type { Impact } from './types'

export const impact = impactData as unknown as Impact
