// Precomputed impact data, imported at build time.
//
// For the `precomputed` data pattern the "fixture" is the real, committed
// dataset generated by scripts/precompute.py against the hosted PolicyEngine
// v1 API (reform policy id 97925, 2026, enhanced CPS). The frontend imports it
// directly; there is no runtime backend.
import impactData from '../../public/data/impact.json'
import type { Impact } from './types'

export const impact = impactData as unknown as Impact
